<?php
// generated by tools/gen.py from tools/langs/Hlc.php — do not edit
// HLC: 48 bits of Unix milliseconds << 16 | 16-bit logical counter (specs/state/README.md).
// PHP ints are signed 64-bit, so ms must stay below 2^47 (the year 6429).
namespace Catboy\Registry;

final class Hlc
{
    public const MAX_DRIFT_MS = 60000;

    public static function encode(int $ms, int $logical): int
    {
        if ($ms < 0 || $ms >= (1 << 47) || $logical < 0 || $logical >= (1 << 16)) {
            throw new \InvalidArgumentException('hlc field out of range');
        }
        return ($ms << 16) | $logical;
    }

    /** @return array{0:int,1:int} [ms, logical] */
    public static function decode(int $h): array
    {
        return [$h >> 16, $h & 0xffff];
    }

    public static function compare(int $a, int $b): int
    {
        return $a <=> $b;
    }

    /** Local event or send: max(now << 16, last + 1). */
    public static function send(int $last, int $nowMs): int
    {
        return max(self::encode($nowMs, 0), $last + 1);
    }

    /** Receive: max(now << 16, last + 1, remote + 1); refuses a remote clock too far ahead. */
    public static function receive(int $last, int $remote, int $nowMs, int $maxDriftMs = self::MAX_DRIFT_MS): int
    {
        if (($remote >> 16) - $nowMs > $maxDriftMs) {
            throw new \RangeException('remote hlc is ' . (($remote >> 16) - $nowMs) . ' ms ahead');
        }
        return max(self::encode($nowMs, 0), $last + 1, $remote + 1);
    }

    /**
     * Order of two changes (specs/state/README.md 3.3): the triple (hlc, instance, change_id).
     * A missing instance (null) counts as 0. change_id compares as an unsigned 128-bit integer.
     */
    public static function compareChange(int $aHlc, ?int $aInstance, string $aChangeId, int $bHlc, ?int $bInstance, string $bChangeId): int
    {
        // strcmp, not <=>: PHP compares numeric strings as numbers, and hex such as "...01e5" reads as 1e5.
        return ($aHlc <=> $bHlc) ?: (($aInstance ?? 0) <=> ($bInstance ?? 0))
            ?: max(-1, min(1, strcmp(self::uuidHex($aChangeId), self::uuidHex($bChangeId))));
    }

    /** 32 lower-case hex digits; equal-length hex strings compare like the 128-bit numbers. */
    private static function uuidHex(string $u): string
    {
        $h = strtolower(str_replace('-', '', $u));
        if (!preg_match('/^[0-9a-f]{32}$/', $h)) {
            throw new \InvalidArgumentException('invalid uuid');
        }
        return $h;
    }
}
