<?php
// generated by tools/gen.py from tools/langs/Ids.php — do not edit
// Port of the Python reference implementation (build/python/oid.py). The results must be
// byte-identical: tests/vectors and the CI job "cross-language" check it. Needs ext-intl.
namespace Catboy\Registry;

final class Ids
{
    private const ASCII_LABEL = '/^[a-z0-9_*-]+$/';
    private const UNRESERVED = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~';
    private const PATH_RAW = "!$&'()*+,;=:@/";

    public static function softwareOid(int $product): string
    {
        return Oid::SOFTWARE . '.' . $product;
    }

    public static function releaseOid(int $product, int $major, int $minor, int $patch): string
    {
        return self::softwareOid($product) . ".1.$major.$minor.$patch";
    }

    public static function channelOid(int $product, int $channel): string
    {
        if (!isset(Oid::CHANNELS[$channel])) {
            throw new \InvalidArgumentException("unknown channel $channel");
        }
        return self::softwareOid($product) . ".2.$channel";
    }

    public static function buildOid(int $product, int $runId): string
    {
        return self::softwareOid($product) . ".3.$runId";
    }

    public static function formatOid(int $product, int $format, int $compat): string
    {
        return self::softwareOid($product) . ".4.$format.$compat";
    }

    /** specs/uuid/namespace.md, algorithm D. Throws \InvalidArgumentException on invalid input. */
    public static function canonicalDomain(string $domain): string
    {
        if (preg_match('//u', $domain) !== 1) {
            throw new \InvalidArgumentException('domain is not valid UTF-8');
        }
        $domain = str_replace(["\u{3002}", "\u{FF0E}", "\u{FF61}"], '.', $domain);
        if (str_ends_with($domain, '.')) {
            $domain = substr($domain, 0, -1);
        }
        if ($domain === '') {
            throw new \InvalidArgumentException('empty domain');
        }
        $out = [];
        foreach (explode('.', $domain) as $label) {
            if ($label === '') {
                throw new \InvalidArgumentException('empty label');
            }
            if (preg_match('/[\x80-\xff]/', $label) !== 1) {
                $label = strtolower($label);
                if (preg_match(self::ASCII_LABEL, $label) !== 1) {
                    throw new \InvalidArgumentException("invalid character in label '$label'");
                }
            } else {
                $flags = IDNA_NONTRANSITIONAL_TO_ASCII | IDNA_USE_STD3_RULES | IDNA_CHECK_BIDI | IDNA_CHECK_CONTEXTJ;
                $a = idn_to_ascii($label, $flags, INTL_IDNA_VARIANT_UTS46, $info);
                if ($a === false || ($info['errors'] ?? 0) !== 0 || str_contains($a, '.')) {
                    throw new \InvalidArgumentException("invalid IDN label '$label'");
                }
                $label = $a;
            }
            if (strlen($label) > 63) {
                throw new \InvalidArgumentException('label longer than 63 octets');
            }
            $out[] = $label;
        }
        $result = implode('.', $out);
        if (strlen($result) > 253) {
            throw new \InvalidArgumentException('domain longer than 253 octets');
        }
        return $result;
    }

    private static function removeDotSegments(string $path): string
    {
        $segs = array_slice(explode('/', $path), 1);
        $out = [];
        $n = count($segs);
        foreach ($segs as $i => $seg) {
            $last = $i === $n - 1;
            if ($seg === '.' || $seg === '..') {
                if ($seg === '..' && $out) {
                    array_pop($out);
                }
                if ($last) {
                    $out[] = '';
                }
            } else {
                $out[] = $seg;
            }
        }
        return '/' . implode('/', $out);
    }

    /** specs/uuid/namespace.md, algorithm P. Throws \InvalidArgumentException on invalid input. */
    public const PATH_PROFILES = ['default', 'nginx', 'nginx-nomerge'];

    /** Algorithm P with a product profile: default, nginx (merge_slashes on, trailing '/' significant), nginx-nomerge. */
    public static function canonicalPath(string $path, string $profile = 'default'): string
    {
        if (!in_array($profile, self::PATH_PROFILES, true)) {
            throw new \InvalidArgumentException("unknown path profile $profile");
        }
        if ($path === '') {
            return '/';
        }
        if ($path[0] !== '/') {
            throw new \InvalidArgumentException("path must start with '/'");
        }
        if (strpbrk($path, '?#') !== false) {
            throw new \InvalidArgumentException("path must not contain '?' or '#'");
        }
        if (preg_match('//u', $path) !== 1) {
            throw new \InvalidArgumentException('path is not valid UTF-8');
        }
        $b = '';
        $len = strlen($path);
        for ($i = 0; $i < $len;) {
            $c = $path[$i];
            if ($c === '%') {
                $h = substr($path, $i + 1, 2);
                if (strlen($h) !== 2 || !ctype_xdigit($h)) {
                    throw new \InvalidArgumentException('invalid percent-escape');
                }
                $v = chr(hexdec($h));
                $b .= strpos(self::UNRESERVED, $v) !== false ? $v : sprintf('%%%02X', ord($v));
                $i += 3;
            } elseif (strpos(self::UNRESERVED . self::PATH_RAW, $c) !== false) {
                $b .= $c;
                $i++;
            } else {
                $b .= sprintf('%%%02X', ord($c));
                $i++;
            }
        }
        if ($profile === 'nginx') { // merge_slashes on: runs of '/' become one, before P5
            $b = preg_replace('#/{2,}#', '/', $b);
        }
        $p = self::removeDotSegments($b);
        if ($profile === 'default') {
            $p = rtrim($p, '/');
        }
        return $p === '' ? '/' : $p;
    }

    /** RFC 9562 version 5 UUID of $name in namespace $ns. */
    public static function uuid5(string $ns, string $name): string
    {
        $n = self::uuidBytes($ns);
        $h = substr(sha1($n . $name, true), 0, 16);
        $h[6] = chr(ord($h[6]) & 0x0f | 0x50);
        $h[8] = chr(ord($h[8]) & 0x3f | 0x80);
        $x = bin2hex($h);
        return substr($x, 0, 8) . '-' . substr($x, 8, 4) . '-' . substr($x, 12, 4) . '-' . substr($x, 16, 4) . '-' . substr($x, 20, 12);
    }

    private static function uuidBytes(string $u): string
    {
        $h = str_replace('-', '', $u);
        if (strlen($u) !== 36 || strlen($h) !== 32 || !ctype_xdigit($h)) {
            throw new \InvalidArgumentException("not a UUID: '$u'");
        }
        return hex2bin($h);
    }

    /** uuid5(CATBOY_NAMESPACE, "catwaf-site:" + canonical domain). */
    public static function siteId(string $domain): string
    {
        return self::uuid5(Oid::CATBOY_NAMESPACE, 'catwaf-site:' . self::canonicalDomain($domain));
    }

    /** uuid5(site id, "route:" + canonical path). */
    public static function routeId(string $siteId, string $path, string $profile = 'default'): string
    {
        return self::uuid5($siteId, 'route:' . self::canonicalPath($path, $profile));
    }

    /** uuid5(CATBOY_NAMESPACE, "<kind>:<key>"). */
    public static function entryId(string $kind, string $key): string
    {
        return self::uuid5(Oid::CATBOY_NAMESPACE, "$kind:$key");
    }

    /** ITU-T X.667 OID form 2.25.<uuid as an unsigned integer>; no bcmath/gmp needed. */
    public static function oidFromUuid(string $uuid): string
    {
        $digits = [0]; // little-endian base 10^9
        foreach (str_split(bin2hex(self::uuidBytes($uuid))) as $hx) {
            $carry = hexdec($hx);
            foreach ($digits as $k => $d) {
                $v = $d * 16 + $carry;
                $digits[$k] = $v % 1000000000;
                $carry = intdiv($v, 1000000000);
            }
            if ($carry > 0) {
                $digits[] = $carry;
            }
        }
        $s = (string) array_pop($digits);
        while ($digits) {
            $s .= sprintf('%09d', array_pop($digits));
        }
        return '2.25.' . $s;
    }
}
