// generated by tools/gen.py from tools/langs/Ids.cs — do not edit
// Port of the Python reference implementation (build/python/oid.py). The results must be
// byte-identical: tests/vectors and the CI job "cross-language" check it.
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Numerics;
using System.Security.Cryptography;
using System.Text;

namespace Catboy.Registry;

public static class Ids
{
    private const string Unreserved = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~";
    private const string PathRaw = Unreserved + "!$&'()*+,;=:@/";
    private const string AsciiLabel = "abcdefghijklmnopqrstuvwxyz0123456789-_*";
    private static readonly IdnMapping Idn = new() { UseStd3AsciiRules = true, AllowUnassigned = false };
    private static readonly UTF8Encoding StrictUtf8 = new(false, true);

    public static string SoftwareOid(int product) => $"{Oid.Software}.{product}";
    public static string ReleaseOid(int product, int major, int minor, int patch) => $"{SoftwareOid(product)}.1.{major}.{minor}.{patch}";
    public static string ChannelOid(int product, int channel) =>
        Oid.Channels.ContainsKey(channel) ? $"{SoftwareOid(product)}.2.{channel}" : throw new ArgumentException($"unknown channel {channel}");
    public static string BuildOid(int product, ulong runId) => $"{SoftwareOid(product)}.3.{runId}";
    public static string FormatOid(int product, int format, int compat) => $"{SoftwareOid(product)}.4.{format}.{compat}";

    /// <summary>specs/uuid/namespace.md, algorithm D. Throws ArgumentException on invalid input.</summary>
    public static string CanonicalDomain(string domain)
    {
        try { StrictUtf8.GetByteCount(domain); } catch (EncoderFallbackException) { throw new ArgumentException("domain is not valid Unicode"); }
        domain = domain.Replace("\u3002", ".").Replace("\uff0e", ".").Replace("\uff61", ".");
        if (domain.EndsWith('.')) domain = domain[..^1];
        if (domain.Length == 0) throw new ArgumentException("empty domain");
        var outLabels = new List<string>();
        foreach (var raw in domain.Split('.'))
        {
            var label = raw;
            if (label.Length == 0) throw new ArgumentException("empty label");
            if (label.All(c => c < 0x80))
            {
                label = label.ToLowerInvariant();
                if (!label.All(c => AsciiLabel.Contains(c))) throw new ArgumentException($"invalid character in label '{label}'");
            }
            else
            {
                try { label = Idn.GetAscii(label); }
                catch (ArgumentException e) { throw new ArgumentException($"invalid IDN label '{raw}': {e.Message}"); }
                if (label.Contains('.')) throw new ArgumentException($"invalid IDN label '{raw}'");
                // .NET skips the UTS #46 CheckHyphens rule; step D5 requires it on the mapped U-label
                var ulabel = Idn.GetUnicode(label);
                if (ulabel.StartsWith('-') || ulabel.EndsWith('-') || (ulabel.Length >= 4 && ulabel[2] == '-' && ulabel[3] == '-'))
                    throw new ArgumentException($"invalid IDN label '{raw}': hyphen rule");
            }
            if (label.Length > 63) throw new ArgumentException("label longer than 63 octets");
            outLabels.Add(label);
        }
        var result = string.Join(".", outLabels);
        if (result.Length > 253) throw new ArgumentException("domain longer than 253 octets");
        return result;
    }

    private static string RemoveDotSegments(string path)
    {
        var segs = path.Split('/').Skip(1).ToArray();
        var outSegs = new List<string>();
        for (var i = 0; i < segs.Length; i++)
        {
            var last = i == segs.Length - 1;
            if (segs[i] == "." || segs[i] == "..")
            {
                if (segs[i] == ".." && outSegs.Count > 0) outSegs.RemoveAt(outSegs.Count - 1);
                if (last) outSegs.Add("");
            }
            else outSegs.Add(segs[i]);
        }
        return "/" + string.Join("/", outSegs);
    }

    private static int Unhex(byte c) => c switch
    {
        >= (byte)'0' and <= (byte)'9' => c - '0',
        >= (byte)'a' and <= (byte)'f' => c - 'a' + 10,
        >= (byte)'A' and <= (byte)'F' => c - 'A' + 10,
        _ => -1,
    };

    /// <summary>specs/uuid/namespace.md, algorithm P. Throws ArgumentException on invalid input.</summary>
    public static readonly string[] PathProfiles = { "default", "nginx", "nginx-nomerge" };

    /// <summary>Algorithm P with a product profile: default, nginx (merge_slashes on, trailing '/' significant), nginx-nomerge.</summary>
    public static string CanonicalPath(string path, string profile = "default")
    {
        if (Array.IndexOf(PathProfiles, profile) < 0) throw new ArgumentException($"unknown path profile {profile}");
        if (path.Length == 0) return "/";
        if (path[0] != '/') throw new ArgumentException("path must start with '/'");
        if (path.IndexOfAny(new[] { '?', '#' }) >= 0) throw new ArgumentException("path must not contain '?' or '#'");
        byte[] b;
        try { b = StrictUtf8.GetBytes(path); } catch (EncoderFallbackException) { throw new ArgumentException("path is not valid Unicode"); }
        var sb = new StringBuilder();
        for (var i = 0; i < b.Length;)
        {
            var c = b[i];
            if (c == '%')
            {
                if (i + 2 >= b.Length) throw new ArgumentException("invalid percent-escape");
                int hi = Unhex(b[i + 1]), lo = Unhex(b[i + 2]);
                if (hi < 0 || lo < 0) throw new ArgumentException("invalid percent-escape");
                var v = (char)(hi << 4 | lo);
                if (Unreserved.Contains(v)) sb.Append(v); else sb.Append('%').Append(((int)v).ToString("X2"));
                i += 3;
            }
            else if (c < 0x80 && PathRaw.Contains((char)c)) { sb.Append((char)c); i++; }
            else { sb.Append('%').Append(c.ToString("X2")); i++; }
        }
        var s = sb.ToString();
        if (profile == "nginx") while (s.Contains("//")) s = s.Replace("//", "/"); // merge_slashes on, before P5
        var p = RemoveDotSegments(s);
        if (profile == "default") p = p.TrimEnd('/');
        return p.Length == 0 ? "/" : p;
    }

    private static byte[] UuidBytes(string u)
    {
        var h = u.Replace("-", "");
        if (u.Length != 36 || h.Length != 32 || !h.All(Uri.IsHexDigit)) throw new ArgumentException($"not a UUID: '{u}'");
        return Convert.FromHexString(h);
    }

    /// <summary>RFC 9562 version 5 UUID of name in namespace ns.</summary>
    public static string Uuid5(string ns, string name)
    {
        var input = UuidBytes(ns).Concat(Encoding.UTF8.GetBytes(name)).ToArray();
        var h = SHA1.HashData(input)[..16];
        h[6] = (byte)(h[6] & 0x0f | 0x50);
        h[8] = (byte)(h[8] & 0x3f | 0x80);
        var x = Convert.ToHexString(h).ToLowerInvariant();
        return $"{x[..8]}-{x[8..12]}-{x[12..16]}-{x[16..20]}-{x[20..]}";
    }

    /// <summary>uuid5(CatboyNamespace, "catwaf-site:" + canonical domain).</summary>
    public static string SiteId(string domain) => Uuid5(Oid.CatboyNamespace, "catwaf-site:" + CanonicalDomain(domain));

    /// <summary>uuid5(site id, "route:" + canonical path).</summary>
    public static string RouteId(string siteId, string path, string profile = "default") => Uuid5(siteId, "route:" + CanonicalPath(path, profile));

    /// <summary>uuid5(CatboyNamespace, kind + ":" + key).</summary>
    public static string EntryId(string kind, string key) => Uuid5(Oid.CatboyNamespace, kind + ":" + key);

    /// <summary>ITU-T X.667 OID form 2.25.&lt;uuid as an unsigned integer&gt;.</summary>
    public static string OidFromUuid(string uuid) =>
        "2.25." + new BigInteger(UuidBytes(uuid), isUnsigned: true, isBigEndian: true).ToString(CultureInfo.InvariantCulture);
}

/// <summary>HLC: 48 bits of Unix milliseconds &lt;&lt; 16 | 16-bit logical counter (specs/state/README.md).</summary>
public static class Hlc
{
    public const ulong MaxDriftMs = 60000;

    public static ulong Encode(ulong ms, ulong logical) =>
        ms < 1UL << 48 && logical < 1UL << 16 ? ms << 16 | logical : throw new ArgumentOutOfRangeException(nameof(ms), "hlc field out of range");

    public static (ulong Ms, ulong Logical) Decode(ulong h) => (h >> 16, h & 0xffff);

    public static int Compare(ulong a, ulong b) => a.CompareTo(b) switch { < 0 => -1, > 0 => 1, _ => 0 };

    /// <summary>Local event or send: max(now &lt;&lt; 16, last + 1).</summary>
    public static ulong Send(ulong last, ulong nowMs) => Math.Max(Encode(nowMs, 0), last + 1);

    /// <summary>Receive: max(now &lt;&lt; 16, last + 1, remote + 1); refuses a remote clock too far ahead.</summary>
    public static ulong Receive(ulong last, ulong remote, ulong nowMs, ulong maxDriftMs = MaxDriftMs)
    {
        if (remote >> 16 > nowMs && (remote >> 16) - nowMs > maxDriftMs)
            throw new InvalidOperationException($"remote hlc is {(remote >> 16) - nowMs} ms ahead");
        return Math.Max(Encode(nowMs, 0), Math.Max(last + 1, remote + 1));
    }

    /// <summary>Order of two changes (specs/state/README.md 3.3): the triple (hlc, instance, change_id).
    /// A missing instance (null) counts as 0. change_id compares as an unsigned 128-bit integer.</summary>
    public static int CompareChange(ulong aHlc, ulong? aInstance, string aChangeId, ulong bHlc, ulong? bInstance, string bChangeId)
    {
        var c = Compare(aHlc, bHlc);
        if (c == 0) c = Compare(aInstance ?? 0, bInstance ?? 0);
        if (c == 0) c = Math.Sign(string.CompareOrdinal(UuidHex(aChangeId), UuidHex(bChangeId)));
        return c;
    }

    private static string UuidHex(string u) =>
        Guid.TryParseExact(u, "D", out var g) ? g.ToString("N") : throw new ArgumentException("invalid uuid", nameof(u));
}
