#!/usr/bin/env python3
"""Render constants (C#, PHP, Python, Go) and docs/arcs.md from registry.yaml into build/.
With pen == null the OID strings contain the literal token <pen>; `--publish` refuses that."""
import sys, pathlib, yaml


def _load(text):
    import datetime as _dt
    d = yaml.safe_load(text) or {}
    for a in d.get('arcs', []):
        if isinstance(a.get('since'), _dt.date): a['since'] = a['since'].isoformat()
    return d


ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "build"
reg = _load((ROOT / "registry.yaml").read_text())
pen = reg.get("pen")
if "--publish" in sys.argv and not pen:
    print("gen: pen is null — refusing to publish"); sys.exit(2)
base = f"1.3.6.1.4.1.{pen if pen else '<pen>'}"
arcs = [a for a in reg["arcs"] if a["status"] != "deprecated" or "--all" in sys.argv]
def const(name): return name.upper().replace("-", "_")

(OUT / "dotnet").mkdir(parents=True, exist_ok=True); (OUT / "php").mkdir(exist_ok=True); (OUT / "python").mkdir(exist_ok=True); (ROOT / "docs").mkdir(exist_ok=True)
cs = ["// generated by tools/gen.py — do not edit", "namespace Catboy.Registry;", "public static class Oid", "{", f'    public const string Enterprise = "{base}";']
if pen:
    import uuid
    ns = str(uuid.uuid5(uuid.NAMESPACE_OID, base))  # specs/uuid/namespace.md
    cs.append(f'    /// <summary>uuid5(NAMESPACE_OID, enterprise arc): fleet UUID namespace (arc .1.6)</summary>\n    public const string CatboyNamespace = "{ns}";')
cs += [f'    /// <summary>{a["purpose"]}</summary>\n    public const string {"".join(w.capitalize() for w in a["name"].split("-"))} = "{base}.{a["oid"]}";' for a in arcs] + ["}"]
(OUT / "dotnet" / "Oid.cs").write_text("\n".join(cs) + "\n")
php = ["<?php", "// generated by tools/gen.py — do not edit", "namespace Catboy\\Registry;", "final class Oid", "{", f"    public const ENTERPRISE = '{base}';"]
if pen: php.append(f"    /** uuid5(NAMESPACE_OID, enterprise arc): fleet UUID namespace (arc .1.6) */\n    public const CATBOY_NAMESPACE = '{ns}';")
php += [f"    /** {a['purpose']} */\n    public const {const(a['name'])} = '{base}.{a['oid']}';" for a in arcs] + ["}"]
(OUT / "php" / "Oid.php").write_text("\n".join(php) + "\n")
py = ['"""generated by tools/gen.py — do not edit"""', f'ENTERPRISE = "{base}"'] + ([f'CATBOY_NAMESPACE = "{ns}"  # uuid5(NAMESPACE_OID, enterprise arc), arc .1.6'] if pen else []) + [f'{const(a["name"])} = "{base}.{a["oid"]}"  # {a["purpose"]}' for a in arcs]
(OUT / "python" / "oid.py").write_text("\n".join(py) + "\n")
# --- software products, channel table, id/HLC helpers (specs/software, specs/uuid, specs/state) --
LANGS = ROOT / "tools" / "langs"
channels = [(c["number"], c["name"]) for c in yaml.safe_load((ROOT / "specs" / "software" / "channels.yaml").read_text())["channels"]]
products = [a for a in arcs if a["oid"].startswith("1.11.") and a["oid"].count(".") == 2]
def camel(name): return "".join(w.capitalize() for w in name.split("-"))
if pen:
    def sw_id(a): return str(uuid.uuid5(uuid.UUID(ns), "software:" + a["name"]))  # kind "software"
    py += ["", "# channel table (.1.11.<product>.2.<channel>), specs/software/channels.yaml",
           "CHANNELS = {" + ", ".join(f'{n}: "{c}"' for n, c in channels) + "}",
           "CHANNEL_NAMES = {v: k for k, v in CHANNELS.items()}"] + [f"CHANNEL_{const(c)} = {n}" for n, c in channels]
    py += ["", "# software products (.1.11.<arc>): arc number, purl, repo, entry id uuid5(ns, 'software:<name>')", "PRODUCTS = {"]
    py += [f'    "{a["name"]}": {{"arc": {a["oid"].rsplit(".", 1)[1]}, "oid": "{base}.{a["oid"]}", "purl": "{a["purl"]}", "repo": "{a.get("repo", "")}", "id": "{sw_id(a)}"'
           + (f', "sysobjectid": "{base}.{a["sysobjectid"]}"' if a.get("sysobjectid") else "") + "}," for a in products] + ["}"]
    (OUT / "python" / "oid.py").write_text("\n".join(py) + "\n" + (LANGS / "helpers.py").read_text())
    cs_extra = ["    /// <summary>channel table (.1.11.&lt;product&gt;.2.&lt;channel&gt;), specs/software/channels.yaml</summary>",
                "    public static readonly System.Collections.Generic.IReadOnlyDictionary<int, string> Channels = new System.Collections.Generic.Dictionary<int, string> { " + ", ".join(f'[{n}] = "{c}"' for n, c in channels) + " };"]
    cs_extra += [f"    public const int Channel{camel(c)} = {n};" for n, c in channels]
    for a in products:
        cs_extra += [f'    public const int {camel(a["name"])}Arc = {a["oid"].rsplit(".", 1)[1]};', f'    public const string {camel(a["name"])}Purl = "{a["purl"]}";', f'    public const string {camel(a["name"])}Id = "{sw_id(a)}";']
    (OUT / "dotnet" / "Oid.cs").write_text("\n".join(cs[:-1] + cs_extra + ["}"]) + "\n")
    (OUT / "dotnet" / "Ids.cs").write_text((LANGS / "Ids.cs").read_text())
    php_extra = ["    /** channel table (.1.11.<product>.2.<channel>), specs/software/channels.yaml */",
                 "    public const CHANNELS = [" + ", ".join(f"{n} => '{c}'" for n, c in channels) + "];"]
    php_extra += [f"    public const CHANNEL_{const(c)} = {n};" for n, c in channels]
    for a in products:
        php_extra += [f'    public const {const(a["name"])}_ARC = {a["oid"].rsplit(".", 1)[1]};', f"    public const {const(a['name'])}_PURL = '{a['purl']}';", f"    public const {const(a['name'])}_ID = '{sw_id(a)}';"]
    (OUT / "php" / "Oid.php").write_text("\n".join(php[:-1] + php_extra + ["}"]) + "\n")
    for f in ("Ids.php", "Hlc.php"): (OUT / "php" / f).write_text((LANGS / f).read_text())
    (OUT / "go").mkdir(exist_ok=True)
    (OUT / "go" / "go.mod").write_text("module github.com/smol-kitten/catboy-registry/go\n\ngo 1.23\n\nrequire golang.org/x/net v0.38.0\n")
    go = ["// Code generated by tools/gen.py; DO NOT EDIT.", "", "// Package registry holds the catboy-registry OIDs, entry-id helpers and HLC helpers.", "package registry", "", "import (",
          *[f'\t"{i}"' for i in ("bytes", "crypto/sha1", "crypto/sha256", "encoding/hex", "errors", "fmt", "math/big", "sort", "strconv", "strings", "unicode/utf8")], "", '\t"golang.org/x/net/idna"', ")", "",
          f'const Enterprise = "{base}"', "", "// CatboyNamespace is uuid5(NAMESPACE_OID, enterprise arc): the fleet UUID namespace (arc .1.6).", f'const CatboyNamespace = "{ns}"', ""]
    go += [f'// {camel(a["name"])}: {a["purpose"]}\nconst {camel(a["name"])} = "{base}.{a["oid"]}"\n' for a in arcs]
    go += ["// Channels is the channel table (.1.11.<product>.2.<channel>), specs/software/channels.yaml.",
           "var Channels = map[int]string{" + ", ".join(f'{n}: "{c}"' for n, c in channels) + "}", ""]
    go += [f"const Channel{camel(c)} = {n}" for n, c in channels] + [""]
    for a in products:
        go += [f'const {camel(a["name"])}Arc = {a["oid"].rsplit(".", 1)[1]}', f'const {camel(a["name"])}Purl = "{a["purl"]}"', f'const {camel(a["name"])}Id = "{sw_id(a)}"']
    (OUT / "go" / "registry.go").write_text("\n".join(go) + "\n" + (LANGS / "helpers.go").read_text())
    print(f"gen: {len(products)} software products, {len(channels)} channels, helpers -> build/{{python,go,php,dotnet}}")

md = ["# Arcs", "", f"Enterprise arc: `{base}` (assignee: {reg['assignee']})", "", "| OID | Name | Status | Owner | Since | Purpose | Spec |", "|---|---|---|---|---|---|---|"]
md += [f"| `{base}.{a['oid']}` | {a['name']} | {a['status']}{(' → `' + base + '.' + a['superseded_by'] + '`') if a.get('superseded_by') else ''} | {a['owner']} | {a['since']} | {a['purpose']} | {('[spec](../' + a['spec'] + ')') if a.get('spec') else ''} |" for a in reg["arcs"]]
md += ["", "## Correcting a wrong entry", "",
       "A merged number never changes its meaning, also when the entry is wrong. To correct it:", "",
       "1. Set `status: deprecated` on the wrong arc and add `superseded_by: <new relative oid>`. Do not change its name, purpose or since.",
       "2. Add a new arc with the next free number and the correct content, in the same pull request.",
       "3. Never reuse the old number. `tools/immutability.py` refuses a change of name, purpose, since, purl or sysobjectid, a removed arc, a deprecated arc that becomes active again and a changed `superseded_by`.",
       "4. Consumers read the generated packages. The deprecated constant disappears from them (it stays in this table), so a build that still uses it fails and shows the change.", "",
       "Software sub-arcs (`.1.11.<n>.*`) are not registry entries: the product mints them by the grammar in [specs/software/README.md](../specs/software/README.md)."]
(ROOT / "docs" / "arcs.md").write_text("\n".join(md) + "\n")
print(f"gen: {len(arcs)} arcs -> build/{{dotnet,php,python}} + docs/arcs.md (pen={pen})")

# --- spec templates -------------------------------------------------------------------------
# templates/**/*.tmpl are rendered with {{PEN}} = the assigned number, or 32473 (the IANA
# documentation PEN, RFC 5612) while pen is null so smilint/asn1tools can run in CI. The rendered
# copies live in build/specs and are labelled DRY-RUN when the number is the placeholder; with
# the real number they are also written to specs/ (the committed, published copy).
TPL = ROOT / "templates"
dry = pen is None
effective = pen if pen else 32473
for t in sorted(TPL.rglob("*.tmpl")):
    out = OUT / "specs" / t.relative_to(TPL).with_suffix("")
    out.parent.mkdir(parents=True, exist_ok=True)
    text = t.read_text().replace("{{PEN}}", str(effective))
    if dry:
        text = ("-- DRY-RUN RENDER: enterprise number 32473 is the IANA documentation PEN (RFC 5612), NOT ours\n" if out.suffix == ".asn1" else "-- DRY-RUN RENDER: 32473 = IANA documentation PEN (RFC 5612), NOT ours\n") + text
    out.write_text(text)
    print(f"gen: rendered {out.relative_to(ROOT)} (pen={'DRY-RUN 32473' if dry else pen})")
    if not dry:
        # with the real number the rendered spec is the published one: committed under specs/,
        # CI fails if it differs from a fresh render (never hand-edit it)
        pub = ROOT / "specs" / t.relative_to(TPL).with_suffix("")
        pub.write_text(f"-- GENERATED by catboy-registry tools/gen.py from templates/{t.relative_to(TPL)} - do not edit\n" + text)
        print(f"gen: published {pub.relative_to(ROOT)}")
