#!/usr/bin/env python3
"""Render constants (C#, PHP, Python) and docs/arcs.md from registry.yaml into build/.
With pen == null the OID strings contain the literal token <pen>; `--publish` refuses that."""
import sys, pathlib, yaml


def _load(text):
    import datetime as _dt
    d = yaml.safe_load(text) or {}
    for a in d.get('arcs', []):
        if isinstance(a.get('since'), _dt.date): a['since'] = a['since'].isoformat()
    return d


ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "build"
reg = _load((ROOT / "registry.yaml").read_text())
pen = reg.get("pen")
if "--publish" in sys.argv and not pen:
    print("gen: pen is null — refusing to publish"); sys.exit(2)
base = f"1.3.6.1.4.1.{pen if pen else '<pen>'}"
arcs = [a for a in reg["arcs"] if a["status"] != "deprecated" or "--all" in sys.argv]
def const(name): return name.upper().replace("-", "_")

(OUT / "dotnet").mkdir(parents=True, exist_ok=True); (OUT / "php").mkdir(exist_ok=True); (OUT / "python").mkdir(exist_ok=True); (ROOT / "docs").mkdir(exist_ok=True)
cs = ["// generated by tools/gen.py — do not edit", "namespace Catboy.Registry;", "public static class Oid", "{", f'    public const string Enterprise = "{base}";']
cs += [f'    /// <summary>{a["purpose"]}</summary>\n    public const string {"".join(w.capitalize() for w in a["name"].split("-"))} = "{base}.{a["oid"]}";' for a in arcs] + ["}"]
(OUT / "dotnet" / "Oid.cs").write_text("\n".join(cs) + "\n")
php = ["<?php", "// generated by tools/gen.py — do not edit", "namespace Catboy\\Registry;", "final class Oid", "{", f"    public const ENTERPRISE = '{base}';"]
php += [f"    /** {a['purpose']} */\n    public const {const(a['name'])} = '{base}.{a['oid']}';" for a in arcs] + ["}"]
(OUT / "php" / "Oid.php").write_text("\n".join(php) + "\n")
py = ['"""generated by tools/gen.py — do not edit"""', f'ENTERPRISE = "{base}"'] + [f'{const(a["name"])} = "{base}.{a["oid"]}"  # {a["purpose"]}' for a in arcs]
(OUT / "python" / "oid.py").write_text("\n".join(py) + "\n")
md = ["# Arcs", "", f"Enterprise arc: `{base}` (assignee: {reg['assignee']})", "", "| OID | Name | Status | Owner | Since | Purpose | Spec |", "|---|---|---|---|---|---|---|"]
md += [f"| `{base}.{a['oid']}` | {a['name']} | {a['status']} | {a['owner']} | {a['since']} | {a['purpose']} | {('[spec](../' + a['spec'] + ')') if a.get('spec') else ''} |" for a in reg["arcs"]]
(ROOT / "docs" / "arcs.md").write_text("\n".join(md) + "\n")
print(f"gen: {len(arcs)} arcs -> build/{{dotnet,php,python}} + docs/arcs.md (pen={pen})")
