#!/usr/bin/env python3
"""Render constants (C#, PHP, Python) and docs/arcs.md from registry.yaml into build/.
With pen == null the OID strings contain the literal token <pen>; `--publish` refuses that."""
import sys, pathlib, yaml


def _load(text):
    import datetime as _dt
    d = yaml.safe_load(text) or {}
    for a in d.get('arcs', []):
        if isinstance(a.get('since'), _dt.date): a['since'] = a['since'].isoformat()
    return d


ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "build"
reg = _load((ROOT / "registry.yaml").read_text())
pen = reg.get("pen")
if "--publish" in sys.argv and not pen:
    print("gen: pen is null — refusing to publish"); sys.exit(2)
base = f"1.3.6.1.4.1.{pen if pen else '<pen>'}"
arcs = [a for a in reg["arcs"] if a["status"] != "deprecated" or "--all" in sys.argv]
def const(name): return name.upper().replace("-", "_")

(OUT / "dotnet").mkdir(parents=True, exist_ok=True); (OUT / "php").mkdir(exist_ok=True); (OUT / "python").mkdir(exist_ok=True); (ROOT / "docs").mkdir(exist_ok=True)
cs = ["// generated by tools/gen.py — do not edit", "namespace Catboy.Registry;", "public static class Oid", "{", f'    public const string Enterprise = "{base}";']
if pen:
    import uuid
    ns = str(uuid.uuid5(uuid.NAMESPACE_OID, base))  # specs/uuid/namespace.md
    cs.append(f'    /// <summary>uuid5(NAMESPACE_OID, enterprise arc): fleet UUID namespace (arc .1.6)</summary>\n    public const string CatboyNamespace = "{ns}";')
cs += [f'    /// <summary>{a["purpose"]}</summary>\n    public const string {"".join(w.capitalize() for w in a["name"].split("-"))} = "{base}.{a["oid"]}";' for a in arcs] + ["}"]
(OUT / "dotnet" / "Oid.cs").write_text("\n".join(cs) + "\n")
php = ["<?php", "// generated by tools/gen.py — do not edit", "namespace Catboy\\Registry;", "final class Oid", "{", f"    public const ENTERPRISE = '{base}';"]
if pen: php.append(f"    /** uuid5(NAMESPACE_OID, enterprise arc): fleet UUID namespace (arc .1.6) */\n    public const CATBOY_NAMESPACE = '{ns}';")
php += [f"    /** {a['purpose']} */\n    public const {const(a['name'])} = '{base}.{a['oid']}';" for a in arcs] + ["}"]
(OUT / "php" / "Oid.php").write_text("\n".join(php) + "\n")
py = ['"""generated by tools/gen.py — do not edit"""', f'ENTERPRISE = "{base}"'] + ([f'CATBOY_NAMESPACE = "{ns}"  # uuid5(NAMESPACE_OID, enterprise arc), arc .1.6'] if pen else []) + [f'{const(a["name"])} = "{base}.{a["oid"]}"  # {a["purpose"]}' for a in arcs]
(OUT / "python" / "oid.py").write_text("\n".join(py) + "\n")
md = ["# Arcs", "", f"Enterprise arc: `{base}` (assignee: {reg['assignee']})", "", "| OID | Name | Status | Owner | Since | Purpose | Spec |", "|---|---|---|---|---|---|---|"]
md += [f"| `{base}.{a['oid']}` | {a['name']} | {a['status']} | {a['owner']} | {a['since']} | {a['purpose']} | {('[spec](../' + a['spec'] + ')') if a.get('spec') else ''} |" for a in reg["arcs"]]
(ROOT / "docs" / "arcs.md").write_text("\n".join(md) + "\n")
print(f"gen: {len(arcs)} arcs -> build/{{dotnet,php,python}} + docs/arcs.md (pen={pen})")

# --- spec templates -------------------------------------------------------------------------
# templates/**/*.tmpl are rendered with {{PEN}} = the assigned number, or 32473 (the IANA
# documentation PEN, RFC 5612) while pen is null so smilint/asn1tools can run in CI. The rendered
# copies live in build/specs and are labelled DRY-RUN when the number is the placeholder; with
# the real number they are also written to specs/ (the committed, published copy).
TPL = ROOT / "templates"
dry = pen is None
effective = pen if pen else 32473
for t in sorted(TPL.rglob("*.tmpl")):
    out = OUT / "specs" / t.relative_to(TPL).with_suffix("")
    out.parent.mkdir(parents=True, exist_ok=True)
    text = t.read_text().replace("{{PEN}}", str(effective))
    if dry:
        text = ("-- DRY-RUN RENDER: enterprise number 32473 is the IANA documentation PEN (RFC 5612), NOT ours\n" if out.suffix == ".asn1" else "-- DRY-RUN RENDER: 32473 = IANA documentation PEN (RFC 5612), NOT ours\n") + text
    out.write_text(text)
    print(f"gen: rendered {out.relative_to(ROOT)} (pen={'DRY-RUN 32473' if dry else pen})")
    if not dry:
        # with the real number the rendered spec is the published one: committed under specs/,
        # CI fails if it differs from a fresh render (never hand-edit it)
        pub = ROOT / "specs" / t.relative_to(TPL).with_suffix("")
        pub.write_text(f"-- GENERATED by catboy-registry tools/gen.py from templates/{t.relative_to(TPL)} - do not edit\n" + text)
        print(f"gen: published {pub.relative_to(ROOT)}")
